function displayPoem(response) {
  new Typewriter("#poem", {
    strings: response.data.answer,
    autoStart: true,
    delay: 1,
    cursor: "",
  });
}

function generatePoem(event) {
  event.preventDefault();

  let instructionsInput = document.querySelector("#users-topic");
  let apiKey = "7odf01a4dd3067tb31ab818f7aa1b23f";
  let prompt = `Generate a poem about ${instructionsInput.value}`;
  let context =
    "You are an experienced poet who only writes short poems. Generate a poem using basic HTML. Separate each line with a <br />. Do not include any titles of the poems. It must not be longer than 6 lines. At the end of the poem use the following signature `This poem was generated by SheCodes AI`. Always put the signature inside of a <strong> element. Always put the signature after the poem. ";
  let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  let poemElement = document.querySelector("#poem");
  poemElement.classList.remove("hidden");
  poemElement.innerHTML = `<div class="generating"> ⏳ Generating a poem for you about ${instructionsInput.value}</div>`;

  axios.get(apiUrl).then(displayPoem);
}
let poemFormElement = document.querySelector("#poem-generator-form");
poemFormElement.addEventListener("submit", generatePoem);
